# Generated by Django 4.2.2 on 2023-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_carrera_materia_nota_correlativa_alumno_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='actual',
            field=models.BooleanField(default=True),
        ),
    ]
