# Generated by Django 4.2.2 on 2023-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_carrera_actual_materia_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno_carrera',
            name='estado',
            field=models.CharField(default='Cursando', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno_materia',
            name='estado',
            field=models.CharField(default='Cursando', max_length=50),
        ),
    ]
