# Generated by Django 4.2.2 on 2023-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alumno_carrera_estado_alter_alumno_materia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
