# Generated by Django 4.2.2 on 2023-09-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_nota_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
